import React, { useState } from 'react';
import api from '../services/api';
import { useAuth } from '../context/AuthContext';
import { FileText, Sparkles, Copy, Check, Download, Loader2, Building, User, Send } from 'lucide-react';
import { motion } from 'framer-motion';

const CoverLetter = () => {
  const { user } = useAuth();
  const [loading, setLoading] = useState(false);
  const [coverLetter, setCoverLetter] = useState('');
  const [copied, setCopied] = useState(false);
  const [error, setError] = useState('');
  
  const [formData, setFormData] = useState({
    company: '',
    role: '',
    job_description: '',
    name: user?.full_name || '',
    email: user?.email || ''
  });

  const handleGenerate = async (e) => {
    e.preventDefault();
    if (!formData.company || !formData.role) {
      setError('Please enter company and role');
      return;
    }
    
    setLoading(true);
    setError('');
    setCoverLetter('');
    
    try {
      const payload = {
        company: formData.company,
        role: formData.role,
        job_description: formData.job_description,
        profile: {
          name: formData.name,
          email: formData.email
        }
      };
      
      const res = await api.post('/api/cover-letter/generate', payload);
      
      if (res.data && res.data.cover_letter) {
        setCoverLetter(res.data.cover_letter);
      } else {
        setError('Failed to generate cover letter');
      }
    } catch (err) {
      console.error('Cover letter error:', err);
      setError(err.response?.data?.detail || 'Error generating cover letter');
    } finally {
      setLoading(false);
    }
  };

  const handleCopy = async () => {
    await navigator.clipboard.writeText(coverLetter);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadPDF = () => {
    const printWindow = window.open('', '_blank');
    printWindow.document.write(`
      <html>
        <head>
          <title>Cover Letter - ${formData.name}</title>
          <style>
            body { font-family: Georgia, serif; padding: 40px; max-width: 800px; margin: 0 auto; line-height: 1.8; }
            p { margin-bottom: 1em; }
          </style>
        </head>
        <body>
          ${coverLetter.split('\n').map(p => `<p>${p}</p>`).join('')}
          <hr style="margin-top: 40px;" />
          <p style="font-size: 12px; color: #666;">Generated by SkillGap.ai</p>
        </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.print();
  };

  return (
    <motion.div className="py-12 px-4 min-h-[calc(100vh-200px)]" initial={{ opacity: 0 }} animate={{ opacity: 1 }}>
      <div className="container mx-auto max-w-[800px]">
        <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} className="mb-8">
          <div className="flex items-center gap-4">
            <div className="w-12 h-12 rounded-xl bg-primary-50 text-primary-600 flex items-center justify-center shadow-sm">
              <FileText size={24} />
            </div>
            <div>
              <h1 className="text-2xl font-bold m-0">Cover Letter Generator</h1>
              <p className="text-secondary m-0">AI-powered cover letter generation</p>
            </div>
          </div>
        </motion.div>

        {error && (
          <div className="bg-error-50 text-error-600 p-4 rounded-xl mb-8 font-medium">
            {error}
          </div>
        )}

        <div className="grid grid-cols-1 gap-8">
          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }} className="card p-8">
            <h3 className="mb-6 flex items-center gap-2 text-lg font-bold">
              <Sparkles size={18} className="text-primary-600" /> Generate Cover Letter
            </h3>
            <form onSubmit={handleGenerate} className="flex flex-col gap-6">
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div>
                  <label className="block mb-2 font-semibold text-secondary text-xs uppercase tracking-wider">Your Name *</label>
                  <input type="text" required value={formData.name} onChange={(e) => setFormData({ ...formData, name: e.target.value })} className="input h-12" placeholder="John Doe" />
                </div>
                <div>
                  <label className="block mb-2 font-semibold text-secondary text-xs uppercase tracking-wider">Your Email</label>
                  <input type="email" value={formData.email} onChange={(e) => setFormData({ ...formData, email: e.target.value })} className="input h-12" placeholder="john@example.com" />
                </div>
              </div>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
                <div>
                  <label className="block mb-2 font-semibold text-secondary text-xs uppercase tracking-wider">Company Name *</label>
                  <input type="text" required value={formData.company} onChange={(e) => setFormData({ ...formData, company: e.target.value })} className="input h-12" placeholder="e.g., Google" />
                </div>
                <div>
                  <label className="block mb-2 font-semibold text-secondary text-xs uppercase tracking-wider">Target Role *</label>
                  <input type="text" required value={formData.role} onChange={(e) => setFormData({ ...formData, role: e.target.value })} className="input h-12" placeholder="e.g., Software Engineer" />
                </div>
              </div>
              <div>
                <label className="block mb-2 font-semibold text-secondary text-xs uppercase tracking-wider">Job Description (Optional)</label>
                <textarea value={formData.job_description} onChange={(e) => setFormData({ ...formData, job_description: e.target.value })} className="input min-h-[120px]" rows={4} placeholder="Paste job description..." />
              </div>
              <button type="submit" disabled={loading || !formData.company || !formData.role} className="btn btn-primary shadow-md mt-2">
                {loading ? <><Loader2 size={18} className="animate-spin" /> Generating...</> : <><Sparkles size={18} /> Generate Cover Letter</>}
              </button>
            </form>
          </motion.div>

          <motion.div initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.2 }} className="card p-8 flex flex-col">
            <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4 mb-8">
              <h3 className="m-0 flex items-center gap-2 text-lg font-bold"><FileText size={18} className="text-primary-600" /> Generated Result</h3>
              {coverLetter && (
                <div className="flex gap-2 w-full sm:w-auto">
                  <button onClick={handleCopy} className="btn btn-secondary flex-1 sm:flex-none text-xs h-auto min-h-0 py-2">
                    {copied ? <Check size={16} /> : <Copy size={16} />} {copied ? 'Copied' : 'Copy'}
                  </button>
                  <button onClick={handleDownloadPDF} className="btn btn-secondary flex-1 sm:flex-none text-xs h-auto min-h-0 py-2">
                    <Download size={16} /> Download
                  </button>
                </div>
              )}
            </div>
            <div className="flex-1 bg-secondary rounded-xl p-8 whitespace-pre-wrap text-base leading-relaxed text-primary border border-neutral-100 min-h-[300px]">
              {coverLetter || (
                <div className="text-center text-tertiary py-12">
                  <FileText size={48} className="opacity-10 mx-auto mb-4" />
                  <p>Fill in the details and click generate to create your personalized cover letter.</p>
                </div>
              )}
            </div>
          </motion.div>
        </div>
      </div>
    </motion.div>
  );
};

export default CoverLetter;