# Static market data — sourced from BLS, Levels.fyi, Glassdoor, PayScale, Robert Half (2025-2026)

INDUSTRY_TRENDS = {
    "Data Science": {
        "growth": [
            {"year": "2021", "demand": 68},
            {"year": "2022", "demand": 78},
            {"year": "2023", "demand": 88},
            {"year": "2024", "demand": 95},
            {"year": "2025", "demand": 100},
            {"year": "2026", "demand": 108},
        ],
        "top_skills": [
            {"skill": "Python", "salary": 132000},
            {"skill": "Machine Learning", "salary": 155000},
            {"skill": "SQL", "salary": 115000},
            {"skill": "Deep Learning", "salary": 168000},
            {"skill": "R", "salary": 118000},
            {"skill": "MLOps", "salary": 162000},
        ],
        "regional_distribution": [
            {"region": "San Francisco", "salary": 175000},
            {"region": "New York", "salary": 160000},
            {"region": "Seattle", "salary": 165000},
            {"region": "Austin", "salary": 140000},
            {"region": "Boston", "salary": 152000},
        ],
        "remote_vs_onsite": [
            {"name": "Remote", "value": 35},
            {"name": "Hybrid", "value": 45},
            {"name": "On-site", "value": 20},
        ],
    },
    "Web Development": {
        "growth": [
            {"year": "2021", "demand": 82},
            {"year": "2022", "demand": 86},
            {"year": "2023", "demand": 90},
            {"year": "2024", "demand": 93},
            {"year": "2025", "demand": 97},
            {"year": "2026", "demand": 100},
        ],
        "top_skills": [
            {"skill": "React", "salary": 128000},
            {"skill": "TypeScript", "salary": 135000},
            {"skill": "Next.js", "salary": 142000},
            {"skill": "Node.js", "salary": 130000},
            {"skill": "GraphQL", "salary": 138000},
            {"skill": "Tailwind CSS", "salary": 118000},
        ],
        "regional_distribution": [
            {"region": "San Francisco", "salary": 165000},
            {"region": "New York", "salary": 155000},
            {"region": "Seattle", "salary": 158000},
            {"region": "London", "salary": 95000},
            {"region": "Berlin", "salary": 82000},
        ],
        "remote_vs_onsite": [
            {"name": "Remote", "value": 40},
            {"name": "Hybrid", "value": 42},
            {"name": "On-site", "value": 18},
        ],
    },
    "Android Development": {
        "growth": [
            {"year": "2021", "demand": 65},
            {"year": "2022", "demand": 70},
            {"year": "2023", "demand": 74},
            {"year": "2024", "demand": 77},
            {"year": "2025", "demand": 80},
            {"year": "2026", "demand": 82},
        ],
        "top_skills": [
            {"skill": "Kotlin", "salary": 135000},
            {"skill": "Jetpack Compose", "salary": 142000},
            {"skill": "Java", "salary": 118000},
            {"skill": "Coroutines", "salary": 138000},
            {"skill": "Retrofit", "salary": 128000},
        ],
        "regional_distribution": [
            {"region": "Mountain View", "salary": 170000},
            {"region": "Seattle", "salary": 155000},
            {"region": "Bangalore", "salary": 45000},
            {"region": "Toronto", "salary": 105000},
        ],
        "remote_vs_onsite": [
            {"name": "Remote", "value": 28},
            {"name": "Hybrid", "value": 48},
            {"name": "On-site", "value": 24},
        ],
    },
    "IOS Development": {
        "growth": [
            {"year": "2021", "demand": 68},
            {"year": "2022", "demand": 72},
            {"year": "2023", "demand": 76},
            {"year": "2024", "demand": 79},
            {"year": "2025", "demand": 82},
            {"year": "2026", "demand": 84},
        ],
        "top_skills": [
            {"skill": "Swift", "salary": 145000},
            {"skill": "SwiftUI", "salary": 148000},
            {"skill": "Combine", "salary": 140000},
            {"skill": "Core Data", "salary": 130000},
            {"skill": "ARKit", "salary": 155000},
        ],
        "regional_distribution": [
            {"region": "Cupertino", "salary": 195000},
            {"region": "San Francisco", "salary": 175000},
            {"region": "Austin", "salary": 145000},
            {"region": "Boston", "salary": 150000},
        ],
        "remote_vs_onsite": [
            {"name": "Remote", "value": 25},
            {"name": "Hybrid", "value": 50},
            {"name": "On-site", "value": 25},
        ],
    },
    "UI-UX Development": {
        "growth": [
            {"year": "2021", "demand": 62},
            {"year": "2022", "demand": 68},
            {"year": "2023", "demand": 74},
            {"year": "2024", "demand": 80},
            {"year": "2025", "demand": 86},
            {"year": "2026", "demand": 92},
        ],
        "top_skills": [
            {"skill": "Figma", "salary": 120000},
            {"skill": "UX Research", "salary": 128000},
            {"skill": "Design Systems", "salary": 135000},
            {"skill": "Prototyping", "salary": 115000},
            {"skill": "Interaction Design", "salary": 125000},
        ],
        "regional_distribution": [
            {"region": "San Francisco", "salary": 155000},
            {"region": "New York", "salary": 145000},
            {"region": "Los Angeles", "salary": 130000},
            {"region": "London", "salary": 88000},
        ],
        "remote_vs_onsite": [
            {"name": "Remote", "value": 38},
            {"name": "Hybrid", "value": 44},
            {"name": "On-site", "value": 18},
        ],
    },
    "Quality Assurance": {
        "growth": [
            {"year": "2021", "demand": 58},
            {"year": "2022", "demand": 64},
            {"year": "2023", "demand": 70},
            {"year": "2024", "demand": 76},
            {"year": "2025", "demand": 82},
            {"year": "2026", "demand": 88},
        ],
        "top_skills": [
            {"skill": "Playwright", "salary": 130000},
            {"skill": "Cypress", "salary": 125000},
            {"skill": "Selenium", "salary": 108000},
            {"skill": "API Testing", "salary": 122000},
            {"skill": "CI/CD", "salary": 135000},
        ],
        "regional_distribution": [
            {"region": "Seattle", "salary": 135000},
            {"region": "Austin", "salary": 120000},
            {"region": "Chicago", "salary": 112000},
            {"region": "Denver", "salary": 115000},
        ],
        "remote_vs_onsite": [
            {"name": "Remote", "value": 42},
            {"name": "Hybrid", "value": 40},
            {"name": "On-site", "value": 18},
        ],
    },
    "DevOps": {
        "growth": [
            {"year": "2021", "demand": 72},
            {"year": "2022", "demand": 82},
            {"year": "2023", "demand": 90},
            {"year": "2024", "demand": 96},
            {"year": "2025", "demand": 102},
            {"year": "2026", "demand": 108},
        ],
        "top_skills": [
            {"skill": "Kubernetes", "salary": 165000},
            {"skill": "Terraform", "salary": 155000},
            {"skill": "AWS", "salary": 148000},
            {"skill": "Docker", "salary": 135000},
            {"skill": "CI/CD", "salary": 140000},
            {"skill": "Linux", "salary": 132000},
        ],
        "regional_distribution": [
            {"region": "San Francisco", "salary": 180000},
            {"region": "Seattle", "salary": 170000},
            {"region": "New York", "salary": 162000},
            {"region": "Austin", "salary": 148000},
        ],
        "remote_vs_onsite": [
            {"name": "Remote", "value": 48},
            {"name": "Hybrid", "value": 35},
            {"name": "On-site", "value": 17},
        ],
    },
    "General": {
        "growth": [
            {"year": "2021", "demand": 50},
            {"year": "2022", "demand": 53},
            {"year": "2023", "demand": 56},
            {"year": "2024", "demand": 59},
            {"year": "2025", "demand": 62},
            {"year": "2026", "demand": 65},
        ],
        "top_skills": [
            {"skill": "Project Management", "salary": 98000},
            {"skill": "Communication", "salary": 75000},
            {"skill": "Data Analysis", "salary": 92000},
            {"skill": "Agile", "salary": 108000},
            {"skill": "Problem Solving", "salary": 88000},
        ],
        "regional_distribution": [
            {"region": "National Avg", "salary": 88000},
            {"region": "Metropolitan", "salary": 110000},
            {"region": "Suburban", "salary": 78000},
            {"region": "Rural", "salary": 65000},
        ],
        "remote_vs_onsite": [
            {"name": "Remote", "value": 22},
            {"name": "Hybrid", "value": 42},
            {"name": "On-site", "value": 36},
        ],
    },
}
